name = "TDAweb"
uuid = "33e9cfd9-3fd8-44a9-876f-d405e84153eb"
version = "0.1.0"
authors = ["vituri <vituri.vituri@gmail.com>"]

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageBinarization = "cbc4b850-ae4b-5111-9e64-df94c024a13d"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MetricSpaces = "737298cd-3e4b-40c4-a4ce-863151543a8d"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36"
PersistenceDiagrams = "90b4794c-894b-4756-a0f8-5efeb5ddf7ae"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Ripserer = "aa79e827-bd0b-42a8-9f10-2b302677a641"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TidierFiles = "8ae5e7a9-bdd3-4c93-9cc3-9df4d5d947db"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
IJulia = "1.34.1"
LinearAlgebra = "1.12.0"
MultivariateStats = "0.10.3"
StatsPlots = "0.15.8"
WebIO = "0.8.21"
