name = "TDAweb"
uuid = "33e9cfd9-3fd8-44a9-876f-d405e84153eb"
authors = ["vituri <vituri.vituri@gmail.com>"]
version = "0.1.0"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MetricSpaces = "737298cd-3e4b-40c4-a4ce-863151543a8d"
PersistenceDiagrams = "90b4794c-894b-4756-a0f8-5efeb5ddf7ae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Ripserer = "aa79e827-bd0b-42a8-9f10-2b302677a641"
